### ISSUE TITLE
Installed files seem odd

### ISSUE THREAD

**Issue by smcv** [hotdoc/hotdoc_devhelp_extension#1]
Steps to reproduce: a project similar to this:

```
<!-- docs/index.md -->
# My Great Project

My project is the best.
```

```
# hotdoc.json
{
  "project_name": "my-great-project",
  "index": "docs/index.md",
  "sitemap": "sitemap.txt",
  "output": "build"
}
```

```
# sitemap.txt
index.md
        misc.md
        other.md
```

(The real project I'm experimenting with here is [apertis-designs](https://git.apertis.org/cgit/apertis-designs.git/).)

Expected result:

```
build/devhelp/my-great-project/my-great-project.devhelp2    refers to index.html (etc.)
build/devhelp/my-great-project/index.html (etc.)
```

suitable for copying `build/devhelp/my-great-project` into `/usr/share/devhelp/books`. The project is titled "My Great Project".

Actual result:

```
build/devhelp/my-great-project/my-great-project.devhelp2    refers to ../my-great-project-html/index.html (etc.)
build/devhelp/my-great-project-html/index.html (etc.)
```

and the project is titled "my-great-project My Great Project".

Now, I might be using this wrong - but it seems to me that the `project_name` ought to be a machine-readable name like `my-great-project` or maybe `MyGreatProject`, whereas the `<h1>` in the index page ought to be the human-readable equivalent. Am I assuming correctly?

**Comment by smcv** [comment]
@MathieuDuponchelle clarified on IRC that the `project_name` is meant to be something human-readable, so my expected results are slightly wrong. The bugs are that the directory name doesn't escape spaces, etc. as `_`, and that the top `<h1>` is redundantly glued onto the project name (I think in practice this means we should probably expect the `project_name` to be the same thing as the top `<h1>`).

**Comment by MathieuDuponchelle** [comment]
Fixed, thanks.
